package com.example.domain.discovery

import com.example.model.ConfidenceLevel
import com.example.model.IdentitySource

object ManufacturerResolver {

    data class VendorResolution(
        val vendor: String?,
        val normalizedVendor: String?,
        val isRandomizedMac: Boolean,
        val confidence: ConfidenceLevel,
        val source: IdentitySource
    )

    // Comprehensive IEEE Registered OUI Database (normalized without colons, uppercase)
    private val OUI_DATABASE = mapOf(
        // Xiaomi / Redmi / POCO
        "F8E079" to "Xiaomi Communications Co Ltd",
        "640980" to "Xiaomi Communications Co Ltd",
        "286C07" to "Xiaomi Communications Co Ltd",
        "ACF7F3" to "Xiaomi Communications Co Ltd",
        "7C1D13" to "Xiaomi Communications Co Ltd",
        "3480B3" to "Xiaomi Communications Co Ltd",
        "506441" to "Xiaomi Communications Co Ltd",
        "18F0E4" to "Xiaomi Communications Co Ltd",
        "0C9838" to "Xiaomi Communications Co Ltd",
        "2034FB" to "Xiaomi Communications Co Ltd",
        "3CBD3E" to "Xiaomi Communications Co Ltd",
        "7811DC" to "Xiaomi Communications Co Ltd",
        "842519" to "Xiaomi Communications Co Ltd",
        "9C99A0" to "Xiaomi Communications Co Ltd",
        "A086C6" to "Xiaomi Communications Co Ltd",
        "D4970B" to "Xiaomi Communications Co Ltd",
        "E446DA" to "Huawei Technologies Co., Ltd",
        "F4C479" to "Huawei Technologies Co., Ltd",
        "001E10" to "Huawei Technologies Co., Ltd",
        "70723C" to "Huawei Technologies Co., Ltd",
        "4455C4" to "Huawei Technologies Co., Ltd",
        "E8CD2D" to "Huawei Technologies Co., Ltd",
        "00259E" to "Huawei Technologies Co., Ltd",
        "00464B" to "Huawei Technologies Co., Ltd",
        "0819A6" to "Huawei Technologies Co., Ltd",
        "104780" to "Huawei Technologies Co., Ltd",
        "200BC7" to "Huawei Technologies Co., Ltd",
        "384C90" to "Huawei Technologies Co., Ltd",
        "4846FB" to "Huawei Technologies Co., Ltd",
        "70A8E3" to "Huawei Technologies Co., Ltd",
        "AC853D" to "Huawei Technologies Co., Ltd",
        "C8D15E" to "Huawei Technologies Co., Ltd",
        "D8490B" to "Huawei Technologies Co., Ltd",

        // Apple (iPhone, iPad, Mac, Apple TV, Watch)
        "3C52A1" to "Apple, Inc.",
        "A483E7" to "Apple, Inc.",
        "BC926B" to "Apple, Inc.",
        "DC2B61" to "Apple, Inc.",
        "ACBC32" to "Apple, Inc.",
        "F01898" to "Apple, Inc.",
        "909F33" to "Apple, Inc.",
        "000393" to "Apple, Inc.",
        "000A27" to "Apple, Inc.",
        "000A95" to "Apple, Inc.",
        "000D93" to "Apple, Inc.",
        "0010FA" to "Apple, Inc.",
        "001451" to "Apple, Inc.",
        "0016CB" to "Apple, Inc.",
        "0017F2" to "Apple, Inc.",
        "0019E3" to "Apple, Inc.",
        "001B63" to "Apple, Inc.",
        "001C10" to "Apple, Inc.",
        "001D4F" to "Apple, Inc.",
        "001E52" to "Apple, Inc.",
        "001F5B" to "Apple, Inc.",
        "001FF3" to "Apple, Inc.",
        "0021E9" to "Apple, Inc.",
        "002241" to "Apple, Inc.",
        "002312" to "Apple, Inc.",
        "002332" to "Apple, Inc.",
        "00236C" to "Apple, Inc.",
        "002436" to "Apple, Inc.",
        "002500" to "Apple, Inc.",
        "00254B" to "Apple, Inc.",
        "002608" to "Apple, Inc.",
        "00264A" to "Apple, Inc.",
        "0026B0" to "Apple, Inc.",
        "0026BB" to "Apple, Inc.",
        "040CCE" to "Apple, Inc.",
        "041552" to "Apple, Inc.",
        "042665" to "Apple, Inc.",
        "04489A" to "Apple, Inc.",
        "044BEE" to "Apple, Inc.",
        "045453" to "Apple, Inc.",
        "0469F8" to "Apple, Inc.",
        "04DB56" to "Apple, Inc.",
        "04E536" to "Apple, Inc.",
        "080007" to "Apple, Inc.",
        "086698" to "Apple, Inc.",
        "087045" to "Apple, Inc.",
        "087402" to "Apple, Inc.",
        "08E689" to "Apple, Inc.",
        "08F4AB" to "Apple, Inc.",
        "0C1539" to "Apple, Inc.",
        "0C3021" to "Apple, Inc.",
        "0C4DE9" to "Apple, Inc.",
        "0C74C2" to "Apple, Inc.",
        "0CB319" to "Apple, Inc.",
        "0CD746" to "Apple, Inc.",
        "101C0C" to "Apple, Inc.",
        "1040F3" to "Apple, Inc.",
        "1093E9" to "Apple, Inc.",
        "109ADD" to "Apple, Inc.",
        "10DDB1" to "Apple, Inc.",
        "14109F" to "Apple, Inc.",
        "14205E" to "Apple, Inc.",
        "145A05" to "Apple, Inc.",
        "148F21" to "Apple, Inc.",
        "1499E2" to "Apple, Inc.",
        "14C213" to "Apple, Inc.",
        "182032" to "Apple, Inc.",
        "183451" to "Apple, Inc.",
        "185936" to "Apple, Inc.",
        "186590" to "Apple, Inc.",
        "18810E" to "Apple, Inc.",
        "189EFC" to "Apple, Inc.",
        "18AF61" to "Apple, Inc.",
        "18E728" to "Apple, Inc.",
        "18EE69" to "Apple, Inc.",
        "203C8F" to "Apple, Inc.",
        "20768F" to "Apple, Inc.",
        "207D74" to "Apple, Inc.",
        "209BCE" to "Apple, Inc.",
        "20A2E4" to "Apple, Inc.",
        "20AB37" to "Apple, Inc.",
        "24240E" to "Apple, Inc.",
        "245B07" to "Apple, Inc.",
        "24A074" to "Apple, Inc.",
        "24A2E1" to "Apple, Inc.",
        "24AB81" to "Apple, Inc.",
        "280B5C" to "Apple, Inc.",
        "285A35" to "Apple, Inc.",
        "286A81" to "Apple, Inc.",
        "286B35" to "Apple, Inc.",
        "28CFE9" to "Apple, Inc.",
        "28E02C" to "Apple, Inc.",
        "28E7CF" to "Apple, Inc.",
        "28ED6A" to "Apple, Inc.",
        "28F076" to "Apple, Inc.",
        "2C1F23" to "Apple, Inc.",
        "2C200B" to "Apple, Inc.",
        "2C3361" to "Apple, Inc.",
        "2CB43A" to "Apple, Inc.",
        "2CF0EE" to "Apple, Inc.",
        "30074D" to "Apple, Inc.",
        "3010E4" to "Apple, Inc.",
        "30636B" to "Apple, Inc.",
        "3090AB" to "Apple, Inc.",
        "30D9D9" to "Apple, Inc.",
        "30F772" to "Apple, Inc.",
        "3408BC" to "Apple, Inc.",
        "34159E" to "Apple, Inc.",
        "34363B" to "Apple, Inc.",
        "345180" to "Apple, Inc.",
        "34A395" to "Apple, Inc.",
        "34AB37" to "Apple, Inc.",
        "34C059" to "Apple, Inc.",
        "34E2FD" to "Apple, Inc.",

        // Samsung Electronics
        "341298" to "Samsung Electronics Co.,Ltd",
        "B072BF" to "Samsung Electronics Co.,Ltd",
        "8CF5A3" to "Samsung Electronics Co.,Ltd",
        "A82BB9" to "Samsung Electronics Co.,Ltd",
        "503275" to "Samsung Electronics Co.,Ltd",
        "0000F0" to "Samsung Electronics Co.,Ltd",
        "0007AB" to "Samsung Electronics Co.,Ltd",
        "000Dae" to "Samsung Electronics Co.,Ltd",
        "001247" to "Samsung Electronics Co.,Ltd",
        "001599" to "Samsung Electronics Co.,Ltd",
        "001632" to "Samsung Electronics Co.,Ltd",
        "00166B" to "Samsung Electronics Co.,Ltd",
        "0017D5" to "Samsung Electronics Co.,Ltd",
        "0018AF" to "Samsung Electronics Co.,Ltd",
        "001A8A" to "Samsung Electronics Co.,Ltd",
        "001BD7" to "Samsung Electronics Co.,Ltd",
        "001C43" to "Samsung Electronics Co.,Ltd",
        "001D25" to "Samsung Electronics Co.,Ltd",
        "001DF6" to "Samsung Electronics Co.,Ltd",
        "001E7D" to "Samsung Electronics Co.,Ltd",
        "001FAA" to "Samsung Electronics Co.,Ltd",
        "002119" to "Samsung Electronics Co.,Ltd",
        "0021D1" to "Samsung Electronics Co.,Ltd",
        "002339" to "Samsung Electronics Co.,Ltd",
        "0023C2" to "Samsung Electronics Co.,Ltd",
        "0023D6" to "Samsung Electronics Co.,Ltd",
        "002454" to "Samsung Electronics Co.,Ltd",
        "002491" to "Samsung Electronics Co.,Ltd",
        "002637" to "Samsung Electronics Co.,Ltd",
        "0418D6" to "Samsung Electronics Co.,Ltd",
        "044EAF" to "Samsung Electronics Co.,Ltd",
        "0808C2" to "Samsung Electronics Co.,Ltd",
        "08373D" to "Samsung Electronics Co.,Ltd",
        "08D46A" to "Samsung Electronics Co.,Ltd",
        "08EE8B" to "Samsung Electronics Co.,Ltd",
        "08FC88" to "Samsung Electronics Co.,Ltd",
        "0C1420" to "Samsung Electronics Co.,Ltd",
        "0CDDA7" to "Samsung Electronics Co.,Ltd",
        "103047" to "Samsung Electronics Co.,Ltd",
        "107719" to "Samsung Electronics Co.,Ltd",
        "141A93" to "Samsung Electronics Co.,Ltd",
        "144D67" to "Samsung Electronics Co.,Ltd",
        "147DDA" to "Samsung Electronics Co.,Ltd",
        "14BB6E" to "Samsung Electronics Co.,Ltd",
        "14F42A" to "Samsung Electronics Co.,Ltd",
        "18227E" to "Samsung Electronics Co.,Ltd",
        "183A2D" to "Samsung Electronics Co.,Ltd",
        "1867B0" to "Samsung Electronics Co.,Ltd",
        "1883BF" to "Samsung Electronics Co.,Ltd",
        "18AF8F" to "Samsung Electronics Co.,Ltd",
        "1C5A3E" to "Samsung Electronics Co.,Ltd",
        "1C62B8" to "Samsung Electronics Co.,Ltd",
        "2013E0" to "Samsung Electronics Co.,Ltd",
        "205531" to "Samsung Electronics Co.,Ltd",
        "20689D" to "Samsung Electronics Co.,Ltd",
        "2400BA" to "Samsung Electronics Co.,Ltd",
        "244B03" to "Samsung Electronics Co.,Ltd",
        "247189" to "Samsung Electronics Co.,Ltd",
        "24DBAC" to "Samsung Electronics Co.,Ltd",
        "28987B" to "Samsung Electronics Co.,Ltd",
        "28CC01" to "Samsung Electronics Co.,Ltd",
        "2C0E3D" to "Samsung Electronics Co.,Ltd",
        "2C4401" to "Samsung Electronics Co.,Ltd",
        "2CF3C8" to "Samsung Electronics Co.,Ltd",
        "301966" to "Samsung Electronics Co.,Ltd",
        "3096FB" to "Samsung Electronics Co.,Ltd",
        "30CDA7" to "Samsung Electronics Co.,Ltd",

        // TP-Link
        "74DA38" to "TP-Link Corporation",
        "50C7BF" to "TP-Link Corporation",
        "C006C3" to "TP-Link Corporation",
        "98DED0" to "TP-Link Corporation",
        "30B5C2" to "TP-Link Corporation",
        "000AEB" to "TP-Link Corporation",
        "001478" to "TP-Link Corporation",
        "0019E0" to "TP-Link Corporation",
        "001D0F" to "TP-Link Corporation",
        "002127" to "TP-Link Corporation",
        "0023CD" to "TP-Link Corporation",
        "002586" to "TP-Link Corporation",
        "002719" to "TP-Link Corporation",
        "0C8063" to "TP-Link Corporation",
        "1027F5" to "TP-Link Corporation",
        "14EB1A" to "TP-Link Corporation",
        "18A6F7" to "TP-Link Corporation",
        "1C3BF3" to "TP-Link Corporation",
        "20DC4A" to "TP-Link Corporation",
        "30DE4B" to "TP-Link Corporation",
        "349672" to "TP-Link Corporation",
        "388345" to "TP-Link Corporation",
        "40169F" to "TP-Link Corporation",
        "54C80F" to "TP-Link Corporation",
        "60E327" to "TP-Link Corporation",
        "704F57" to "TP-Link Corporation",
        "7844FD" to "TP-Link Corporation",
        "8416F9" to "TP-Link Corporation",
        "8CF228" to "TP-Link Corporation",
        "940853" to "TP-Link Corporation",
        "A42BB0" to "TP-Link Corporation",
        "AC84C6" to "TP-Link Corporation",
        "B04E26" to "TP-Link Corporation",
        "B4B024" to "TP-Link Corporation",
        "C46E1F" to "TP-Link Corporation",
        "CC32E5" to "TP-Link Corporation",
        "D46E0E" to "TP-Link Corporation",
        "D80D17" to "TP-Link Corporation",
        "E4C32A" to "TP-Link Corporation",
        "EC086B" to "TP-Link Corporation",
        "F4F26D" to "TP-Link Corporation",

        // Google
        "546009" to "Google, Inc.",
        "F4F5D8" to "Google, Inc.",
        "D83134" to "Google, Inc.",
        "089E08" to "Google, Inc.",
        "001A11" to "Google, Inc.",
        "18B430" to "Google, Inc.",
        "20DFB9" to "Google, Inc.",
        "3C5AB4" to "Google, Inc.",
        "48D6D5" to "Google, Inc.",
        "641666" to "Google, Inc.",
        "703EAC" to "Google, Inc.",
        "94EB2C" to "Google, Inc.",
        "A47733" to "Google, Inc.",
        "AC63BE" to "Google, Inc.",
        "D4E6B7" to "Google, Inc.",
        "E4F042" to "Google, Inc.",
        "F88F8A" to "Google, Inc.",

        // Amazon
        "44650D" to "Amazon Technologies Inc.",
        "6837E9" to "Amazon Technologies Inc.",
        "F0D2F1" to "Amazon Technologies Inc.",
        "00FC8B" to "Amazon Technologies Inc.",
        "0C47C9" to "Amazon Technologies Inc.",
        "18742E" to "Amazon Technologies Inc.",
        "34D270" to "Amazon Technologies Inc.",
        "38F7CD" to "Amazon Technologies Inc.",
        "40B4CD" to "Amazon Technologies Inc.",
        "50F5DA" to "Amazon Technologies Inc.",
        "6854FD" to "Amazon Technologies Inc.",
        "747548" to "Amazon Technologies Inc.",
        "84D6D0" to "Amazon Technologies Inc.",
        "AC63BE" to "Amazon Technologies Inc.",
        "CCF735" to "Amazon Technologies Inc.",
        "FC65DE" to "Amazon Technologies Inc.",

        // Sony
        "001A79" to "Sony Interactive Entertainment",
        "00014A" to "Sony Corporation",
        "00041F" to "Sony Corporation",
        "000E07" to "Sony Corporation",
        "0013A9" to "Sony Corporation",
        "0015C1" to "Sony Corporation",
        "0019C5" to "Sony Corporation",
        "001D28" to "Sony Corporation",
        "0024BE" to "Sony Corporation",
        "0498F3" to "Sony Interactive Entertainment",
        "0CFE45" to "Sony Interactive Entertainment",
        "280D41" to "Sony Interactive Entertainment",
        "709E29" to "Sony Interactive Entertainment",
        "FC0F4B" to "Sony Interactive Entertainment",

        // Microsoft
        "00155D" to "Microsoft Corporation",
        "0003FF" to "Microsoft Corporation",
        "000D3A" to "Microsoft Corporation",
        "00125A" to "Microsoft Corporation",
        "0017FA" to "Microsoft Corporation",
        "002248" to "Microsoft Corporation",
        "281878" to "Microsoft Corporation",
        "7C1E52" to "Microsoft Corporation",
        "DCB4C4" to "Microsoft Corporation",

        // Dell
        "001422" to "Dell Inc.",
        "001B21" to "Dell Inc.",
        "002170" to "Dell Inc.",
        "180373" to "Dell Inc.",
        "847BEB" to "Dell Inc.",
        "00065B" to "Dell Inc.",
        "000874" to "Dell Inc.",
        "000BDB" to "Dell Inc.",
        "000F1F" to "Dell Inc.",
        "001143" to "Dell Inc.",
        "00123F" to "Dell Inc.",
        "001372" to "Dell Inc.",
        "0015C5" to "Dell Inc.",
        "0016F0" to "Dell Inc.",
        "00188B" to "Dell Inc.",
        "0019B9" to "Dell Inc.",
        "001A6B" to "Dell Inc.",
        "001C23" to "Dell Inc.",
        "001D09" to "Dell Inc.",
        "001E4F" to "Dell Inc.",
        "002219" to "Dell Inc.",
        "0023AE" to "Dell Inc.",
        "0024E8" to "Dell Inc.",
        "0026B9" to "Dell Inc.",
        "14FEB5" to "Dell Inc.",
        "24B6FD" to "Dell Inc.",
        "3417EB" to "Dell Inc.",
        "484D7E" to "Dell Inc.",
        "74867A" to "Dell Inc.",
        "BC305B" to "Dell Inc.",

        // HP / Hewlett-Packard
        "0008C7" to "HP Inc.",
        "3C4A92" to "HP Inc.",
        "0001E6" to "Hewlett Packard Enterprise",
        "000B86" to "Hewlett Packard Enterprise",
        "00110A" to "HP Inc.",
        "001438" to "HP Inc.",
        "001635" to "HP Inc.",
        "001708" to "HP Inc.",
        "0018FE" to "HP Inc.",
        "001A4B" to "HP Inc.",
        "001CC4" to "HP Inc.",
        "001E0B" to "HP Inc.",
        "001F29" to "HP Inc.",
        "00215A" to "HP Inc.",
        "002264" to "HP Inc.",
        "00237D" to "HP Inc.",
        "002481" to "HP Inc.",
        "0025B3" to "HP Inc.",
        "10604B" to "HP Inc.",
        "2C44FD" to "HP Inc.",
        "30E171" to "HP Inc.",
        "68B599" to "HP Inc.",
        "705A0F" to "HP Inc.",
        "9C8E99" to "HP Inc.",

        // Lenovo
        "0012FE" to "Lenovo",
        "005080" to "Lenovo",
        "A44E31" to "Lenovo",
        "CD4B15" to "Lenovo",
        "001A64" to "Lenovo",
        "0456E5" to "Lenovo",
        "081196" to "Lenovo",
        "105932" to "Lenovo",
        "28565A" to "Lenovo",
        "3052CB" to "Lenovo",
        "3C970E" to "Lenovo",
        "54EE75" to "Lenovo",
        "600292" to "Lenovo",
        "680571" to "Lenovo",
        "7072CF" to "Lenovo",
        "88708C" to "Lenovo",

        // Intel
        "001302" to "Intel Corporation",
        "001E64" to "Intel Corporation",
        "340286" to "Intel Corporation",
        "8086F2" to "Intel Corporation",
        "A0369F" to "Intel Corporation",
        "0002B3" to "Intel Corporation",
        "000347" to "Intel Corporation",
        "000423" to "Intel Corporation",
        "000C76" to "Intel Corporation",
        "000E0C" to "Intel Corporation",
        "001111" to "Intel Corporation",
        "0012F0" to "Intel Corporation",
        "0013E8" to "Intel Corporation",
        "001500" to "Intel Corporation",
        "001676" to "Intel Corporation",
        "0019D1" to "Intel Corporation",
        "001B77" to "Intel Corporation",
        "001C2B" to "Intel Corporation",
        "001D43" to "Intel Corporation",
        "001D60" to "Intel Corporation",
        "00215C" to "Intel Corporation",
        "00216A" to "Intel Corporation",
        "0022FA" to "Intel Corporation",
        "002315" to "Intel Corporation",
        "0024D7" to "Intel Corporation",
        "002710" to "Intel Corporation",
        "04ED33" to "Intel Corporation",
        "081196" to "Intel Corporation",
        "1002B5" to "Intel Corporation",

        // Realtek
        "000767" to "Realtek Semiconductor Corp.",
        "000E08" to "Realtek Semiconductor Corp.",
        "00E04C" to "Realtek Semiconductor Corp.",
        "525400" to "QEMU / Realtek Virtual NIC",

        // ASUS
        "00112F" to "ASUSTeK Computer Inc.",
        "0013D4" to "ASUSTeK Computer Inc.",
        "2C56DC" to "ASUSTeK Computer Inc.",
        "0015F2" to "ASUSTeK Computer Inc.",
        "0018F3" to "ASUSTeK Computer Inc.",
        "001BFC" to "ASUSTeK Computer Inc.",
        "001E8C" to "ASUSTeK Computer Inc.",
        "002215" to "ASUSTeK Computer Inc.",
        "002354" to "ASUSTeK Computer Inc.",
        "00248C" to "ASUSTeK Computer Inc.",
        "002618" to "ASUSTeK Computer Inc.",
        "049226" to "ASUSTeK Computer Inc.",
        "04D4C4" to "ASUSTeK Computer Inc.",
        "086266" to "ASUSTeK Computer Inc.",
        "107B44" to "ASUSTeK Computer Inc.",
        "1C872C" to "ASUSTeK Computer Inc.",
        "244BFE" to "ASUSTeK Computer Inc.",
        "3085A9" to "ASUSTeK Computer Inc.",

        // Netgear
        "00095B" to "Netgear",
        "000F66" to "Netgear",
        "28C68E" to "Netgear",
        "00146C" to "Netgear",
        "00184D" to "Netgear",
        "001B2F" to "Netgear",
        "001E2A" to "Netgear",
        "001F33" to "Netgear",
        "00223F" to "Netgear",
        "0024B2" to "Netgear",
        "0026F2" to "Netgear",
        "04A151" to "Netgear",
        "100C6B" to "Netgear",
        "204E7F" to "Netgear",
        "2C3033" to "Netgear",
        "30469A" to "Netgear",

        // Cisco / Linksys
        "00000C" to "Cisco Systems, Inc.",
        "000142" to "Cisco Systems, Inc.",
        "000143" to "Cisco Systems, Inc.",
        "000196" to "Cisco Systems, Inc.",
        "000197" to "Cisco Systems, Inc.",
        "000216" to "Cisco Systems, Inc.",
        "000217" to "Cisco Systems, Inc.",
        "00027D" to "Cisco Systems, Inc.",
        "0002B9" to "Cisco Systems, Inc.",
        "0002BA" to "Cisco Systems, Inc.",
        "0002FC" to "Cisco Systems, Inc.",
        "00036B" to "Cisco Systems, Inc.",
        "0003E3" to "Cisco Systems, Inc.",
        "000427" to "Cisco Systems, Inc.",
        "00044D" to "Cisco Systems, Inc.",
        "00049F" to "Cisco Systems, Inc.",
        "000531" to "Cisco Systems, Inc.",
        "000573" to "Cisco Systems, Inc.",
        "00059A" to "Cisco Systems, Inc.",
        "000628" to "Cisco Systems, Inc.",
        "000652" to "Cisco Systems, Inc.",
        "0006D6" to "Cisco Systems, Inc.",
        "00070E" to "Cisco Systems, Inc.",
        "000784" to "Cisco Systems, Inc.",
        "000820" to "Cisco Systems, Inc.",
        "0008A3" to "Cisco Systems, Inc.",
        "0008E3" to "Cisco Systems, Inc.",
        "000943" to "Cisco Systems, Inc.",
        "0009B7" to "Cisco Systems, Inc.",
        "000A41" to "Cisco Systems, Inc.",
        "000A8A" to "Cisco Systems, Inc.",
        "000BB5" to "Cisco Systems, Inc.",
        "000C85" to "Cisco Systems, Inc.",
        "000CEA" to "Cisco Systems, Inc.",
        "000D28" to "Cisco Systems, Inc.",
        "000D65" to "Cisco Systems, Inc.",
        "000E38" to "Cisco Systems, Inc.",
        "000E83" to "Cisco Systems, Inc.",
        "000ED7" to "Cisco Systems, Inc.",
        "000F23" to "Cisco Systems, Inc.",
        "000F90" to "Cisco Systems, Inc.",
        "001120" to "Cisco Systems, Inc.",
        "00115C" to "Cisco Systems, Inc.",
        "001192" to "Cisco Systems, Inc.",
        "001201" to "Cisco Systems, Inc.",
        "001243" to "Cisco Systems, Inc.",
        "00127F" to "Cisco Systems, Inc.",
        "001319" to "Cisco Systems, Inc.",
        "00135F" to "Cisco Systems, Inc.",
        "00141C" to "Cisco Systems, Inc.",
        "001469" to "Cisco Systems, Inc.",
        "0014A8" to "Cisco Systems, Inc.",
        "00152B" to "Cisco Systems, Inc.",
        "001562" to "Cisco Systems, Inc.",
        "001646" to "Cisco Systems, Inc.",
        "00169C" to "Cisco Systems, Inc.",
        "00170E" to "Cisco Systems, Inc.",
        "001759" to "Cisco Systems, Inc.",
        "001818" to "Cisco Systems, Inc.",
        "001874" to "Cisco Systems, Inc.",
        "0018B9" to "Cisco Systems, Inc.",
        "001906" to "Cisco Systems, Inc.",
        "001955" to "Cisco Systems, Inc.",
        "001A2F" to "Cisco Systems, Inc.",
        "001A6C" to "Cisco Systems, Inc.",
        "001AA9" to "Cisco Systems, Inc.",
        "001B0D" to "Cisco Systems, Inc.",
        "001B53" to "Cisco Systems, Inc.",
        "001BD4" to "Cisco Systems, Inc.",
        "001C0E" to "Cisco Systems, Inc.",
        "001C57" to "Cisco Systems, Inc.",
        "001CB0" to "Cisco Systems, Inc.",
        "001D45" to "Cisco Systems, Inc.",
        "001D70" to "Cisco Systems, Inc.",
        "001DA1" to "Cisco Systems, Inc.",
        "001E13" to "Cisco Systems, Inc.",
        "001E49" to "Cisco Systems, Inc.",
        "001E7A" to "Cisco Systems, Inc.",
        "001EB6" to "Cisco Systems, Inc.",
        "001F26" to "Cisco Systems, Inc.",
        "001F6C" to "Cisco Systems, Inc.",
        "001F9E" to "Cisco Systems, Inc.",
        "001FC9" to "Cisco Systems, Inc.",
        "00211B" to "Cisco Systems, Inc.",
        "002155" to "Cisco Systems, Inc.",
        "0021A0" to "Cisco Systems, Inc.",
        "0021D7" to "Cisco Systems, Inc.",
        "002255" to "Cisco Systems, Inc.",
        "002290" to "Cisco Systems, Inc.",
        "0022BD" to "Cisco Systems, Inc.",
        "002304" to "Cisco Systems, Inc.",
        "002333" to "Cisco Systems, Inc.",
        "00235E" to "Cisco Systems, Inc.",
        "0023AC" to "Cisco Systems, Inc.",
        "0023EB" to "Cisco Systems, Inc.",
        "002413" to "Cisco Systems, Inc.",
        "002450" to "Cisco Systems, Inc.",
        "002497" to "Cisco Systems, Inc.",
        "0024C4" to "Cisco Systems, Inc.",
        "0024F7" to "Cisco Systems, Inc.",
        "002545" to "Cisco Systems, Inc.",
        "002583" to "Cisco Systems, Inc.",
        "00260B" to "Cisco Systems, Inc.",
        "002644" to "Cisco Systems, Inc.",
        "002698" to "Cisco Systems, Inc.",

        // D-Link
        "00055D" to "D-Link Systems, Inc.",
        "000D88" to "D-Link Systems, Inc.",
        "001195" to "D-Link Systems, Inc.",
        "001346" to "D-Link Systems, Inc.",
        "0015E9" to "D-Link Systems, Inc.",
        "00179A" to "D-Link Systems, Inc.",
        "00195B" to "D-Link Systems, Inc.",
        "001B11" to "D-Link Systems, Inc.",
        "001CF0" to "D-Link Systems, Inc.",
        "001E58" to "D-Link Systems, Inc.",
        "002191" to "D-Link Systems, Inc.",
        "0022B0" to "D-Link Systems, Inc.",
        "002401" to "D-Link Systems, Inc.",
        "00265A" to "D-Link Systems, Inc.",
        "14D64D" to "D-Link Systems, Inc.",
        "1C7EE5" to "D-Link Systems, Inc.",
        "28107B" to "D-Link Systems, Inc.",

        // IoT / Embedded / Smart Home
        "B827EB" to "Raspberry Pi Foundation",
        "DCA632" to "Raspberry Pi Foundation",
        "28CDC1" to "Raspberry Pi Foundation",
        "E45F01" to "Raspberry Pi Foundation",
        "2462AB" to "Espressif Systems",
        "30AEA4" to "Espressif Systems",
        "483FDA" to "Espressif Systems",
        "18FE34" to "Espressif Systems",
        "94B40F" to "Espressif Systems",
        "240AC4" to "Espressif Systems",
        "24B2DE" to "Espressif Systems",
        "2C3AE8" to "Espressif Systems",
        "3C71BF" to "Espressif Systems",
        "40F520" to "Espressif Systems",
        "4CEBD6" to "Espressif Systems",
        "5443B2" to "Espressif Systems",
        "600194" to "Espressif Systems",
        "68C63A" to "Espressif Systems",
        "70039F" to "Espressif Systems",
        "7C9EBD" to "Espressif Systems",
        "807D3A" to "Espressif Systems",
        "840D8E" to "Espressif Systems",
        "84F3EB" to "Espressif Systems",
        "8C4B14" to "Espressif Systems",
        "9097D5" to "Espressif Systems",
        "A020A6" to "Espressif Systems",
        "A4CF12" to "Espressif Systems",
        "AC67B2" to "Espressif Systems",
        "B4E62D" to "Espressif Systems",
        "BCDD9C" to "Espressif Systems",
        "C44F33" to "Espressif Systems",
        "CC50E3" to "Espressif Systems",
        "D8A01D" to "Espressif Systems",
        "DC4F22" to "Espressif Systems",
        "E09806" to "Espressif Systems",
        "E8DB84" to "Espressif Systems",
        "EC94CB" to "Espressif Systems",

        // Roku & Sonos & Smart TV
        "000D4B" to "Roku, Inc.",
        "080581" to "Roku, Inc.",
        "84EA99" to "Roku, Inc.",
        "B0A737" to "Roku, Inc.",
        "CC6D10" to "Roku, Inc.",
        "D83134" to "Roku, Inc.",
        "000E58" to "Sonos, Inc.",
        "48A6B8" to "Sonos, Inc.",
        "5C0979" to "Sonos, Inc.",
        "7828CA" to "Sonos, Inc.",
        "949F3E" to "Sonos, Inc.",
        "B8E937" to "Sonos, Inc.",

        // LG Electronics
        "0005F9" to "LG Electronics",
        "0019C7" to "LG Electronics",
        "001C62" to "LG Electronics",
        "001E75" to "LG Electronics",
        "001F6B" to "LG Electronics",
        "0021FB" to "LG Electronics",
        "002483" to "LG Electronics",
        "0026E2" to "LG Electronics",
        "08FC52" to "LG Electronics",
        "10F9EE" to "LG Electronics",
        "14C913" to "LG Electronics",
        "203D66" to "LG Electronics",

        // OnePlus, OPPO, Vivo, ZTE
        "001E73" to "ZTE Corporation",
        "002293" to "ZTE Corporation",
        "D0154A" to "ZTE Corporation",
        "E0CB1D" to "OnePlus Technology",
        "980CA5" to "OnePlus Technology",
        "70BF92" to "Guangdong OPPO Mobile",
        "2CAB37" to "Guangdong OPPO Mobile",
        "40A2DB" to "Vivo Mobile",
        "784F43" to "Vivo Mobile",

        // Synology & QNAP & Ubiquiti
        "001132" to "Synology Incorporated",
        "00089B" to "QNAP Systems, Inc.",
        "24A43C" to "Ubiquiti Networks Inc.",
        "002722" to "Ubiquiti Networks Inc.",
        "0418D6" to "Ubiquiti Networks Inc.",
        "687251" to "Ubiquiti Networks Inc.",
        "7483C2" to "Ubiquiti Networks Inc.",
        "788A20" to "Ubiquiti Networks Inc.",
        "802AA8" to "Ubiquiti Networks Inc.",
        "AC8BA9" to "Ubiquiti Networks Inc.",
        "B4FBE4" to "Ubiquiti Networks Inc.",
        "DC9FDB" to "Ubiquiti Networks Inc.",
        "E063DA" to "Ubiquiti Networks Inc.",
        "F09FC2" to "Ubiquiti Networks Inc.",

        // Nintendo & NVIDIA & VMware
        "0009BF" to "Nintendo Co., Ltd.",
        "0017AB" to "Nintendo Co., Ltd.",
        "001F32" to "Nintendo Co., Ltd.",
        "0022AA" to "Nintendo Co., Ltd.",
        "00241E" to "Nintendo Co., Ltd.",
        "0025A0" to "Nintendo Co., Ltd.",
        "002659" to "Nintendo Co., Ltd.",
        "00044B" to "NVIDIA Corporation",
        "005056" to "VMware, Inc.",
        "000C29" to "VMware, Inc."
    )

    /**
     * Checks if a MAC address has the locally administered / randomized bit set (bit 1 of first byte).
     * Standard IEEE 802: If (byte0 & 0x02) != 0, it is a Locally Administered Address (LAA / Randomized).
     */
    fun isLocallyAdministeredOrRandomized(mac: String?): Boolean {
        if (mac.isNullOrBlank()) return false
        val clean = mac.replace(":", "").replace("-", "").trim()
        if (clean.length < 2) return false
        val firstByte = clean.substring(0, 2).toIntOrNull(16) ?: return false
        // Bit 1 (0x02) indicates locally administered (randomized) address
        return (firstByte and 0x02) != 0
    }

    /**
     * Resolves vendor information from hardware MAC address with strict randomization detection.
     */
    fun resolveVendorFromMac(mac: String?): VendorResolution {
        if (mac.isNullOrBlank()) {
            return VendorResolution(
                vendor = null,
                normalizedVendor = null,
                isRandomizedMac = false,
                confidence = ConfidenceLevel.NONE,
                source = IdentitySource.UNKNOWN
            )
        }

        val cleanMac = mac.replace(":", "").replace("-", "").trim().uppercase()
        if (cleanMac.length < 6) {
            return VendorResolution(
                vendor = null,
                normalizedVendor = null,
                isRandomizedMac = false,
                confidence = ConfidenceLevel.NONE,
                source = IdentitySource.UNKNOWN
            )
        }

        val isRandomized = isLocallyAdministeredOrRandomized(cleanMac)
        if (isRandomized) {
            return VendorResolution(
                vendor = "Randomized MAC (Privacy Address)",
                normalizedVendor = "Randomized (Privacy)",
                isRandomizedMac = true,
                confidence = ConfidenceLevel.LOW,
                source = IdentitySource.MAC_OUI
            )
        }

        val prefix = cleanMac.substring(0, 6)
        val rawVendor = OUI_DATABASE[prefix]

        if (rawVendor != null) {
            val normalized = normalizeVendor(rawVendor)
            return VendorResolution(
                vendor = rawVendor,
                normalizedVendor = normalized,
                isRandomizedMac = false,
                confidence = ConfidenceLevel.HIGH,
                source = IdentitySource.MAC_OUI
            )
        }

        return VendorResolution(
            vendor = null,
            normalizedVendor = null,
            isRandomizedMac = false,
            confidence = ConfidenceLevel.NONE,
            source = IdentitySource.UNKNOWN
        )
    }

    /**
     * Normalizes complex corporate names to clean brand identifiers.
     */
    fun normalizeVendor(vendor: String?): String? {
        if (vendor.isNullOrBlank()) return null
        val clean = vendor.trim()
        if (clean.equals("Unknown manufacturer", ignoreCase = true) ||
            clean.equals("Unknown", ignoreCase = true) ||
            clean.equals("Unavailable", ignoreCase = true)
        ) {
            return null
        }

        return when {
            clean.contains("Xiaomi", ignoreCase = true) -> "Xiaomi"
            clean.contains("Apple", ignoreCase = true) -> "Apple"
            clean.contains("Samsung", ignoreCase = true) -> "Samsung"
            clean.contains("Huawei", ignoreCase = true) -> "Huawei"
            clean.contains("TP-Link", ignoreCase = true) || clean.contains("TPLink", ignoreCase = true) -> "TP-Link"
            clean.contains("Google", ignoreCase = true) -> "Google"
            clean.contains("Amazon", ignoreCase = true) -> "Amazon"
            clean.contains("Sony", ignoreCase = true) -> "Sony"
            clean.contains("Microsoft", ignoreCase = true) -> "Microsoft"
            clean.contains("Dell", ignoreCase = true) -> "Dell"
            clean.contains("Intel", ignoreCase = true) -> "Intel"
            clean.contains("Lenovo", ignoreCase = true) -> "Lenovo"
            clean.contains("ZTE", ignoreCase = true) -> "ZTE"
            clean.contains("Realtek", ignoreCase = true) -> "Realtek"
            clean.contains("Raspberry", ignoreCase = true) -> "Raspberry Pi"
            clean.contains("Espressif", ignoreCase = true) -> "Espressif"
            clean.contains("NVIDIA", ignoreCase = true) -> "NVIDIA"
            clean.contains("VMware", ignoreCase = true) -> "VMware"
            clean.contains("Cisco", ignoreCase = true) -> "Cisco"
            clean.contains("Asus", ignoreCase = true) -> "ASUS"
            clean.contains("Netgear", ignoreCase = true) -> "Netgear"
            clean.contains("D-Link", ignoreCase = true) -> "D-Link"
            clean.contains("Linksys", ignoreCase = true) -> "Linksys"
            clean.contains("HP", ignoreCase = true) || clean.contains("Hewlett", ignoreCase = true) -> "HP"
            clean.contains("OnePlus", ignoreCase = true) -> "OnePlus"
            clean.contains("Oppo", ignoreCase = true) -> "OPPO"
            clean.contains("Vivo", ignoreCase = true) -> "Vivo"
            clean.contains("Roku", ignoreCase = true) -> "Roku"
            clean.contains("Sonos", ignoreCase = true) -> "Sonos"
            clean.contains("LG", ignoreCase = true) -> "LG"
            clean.contains("Synology", ignoreCase = true) -> "Synology"
            clean.contains("QNAP", ignoreCase = true) -> "QNAP"
            clean.contains("Ubiquiti", ignoreCase = true) -> "Ubiquiti"
            clean.contains("Nintendo", ignoreCase = true) -> "Nintendo"
            clean.contains("Philips", ignoreCase = true) -> "Philips"
            else -> {
                clean.replace(Regex("(?i)\\s+(co\\.?|ltd\\.?|inc\\.?|corp\\.?|corporation|technologies|electronics|foundation|systems|incorporated|enterprise)$"), "").trim()
            }
        }
    }
}
